# Generated by Django 4.2.3 on 2023-07-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mychat.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='friend',
            field=models.ManyToManyField(related_name='my_friends', to='mychat.friends'),
        ),
    ]
